SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS USER_MASTER (
    USER_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR(255) NOT NULL,
    ROLE            VARCHAR(30) NOT NULL,
    STATUS          CHAR(1) NOT NULL DEFAULT 'A',
    CREATED_ON      TIMESTAMP NOT NULL DEFAULT now()
);
