SET search_path TO "motorportal";

CREATE TABLE IF NOT EXISTS PRODUCT_MASTER (
    PRODUCT_ID      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_CODE    VARCHAR(20) NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR(60) NOT NULL,
    STATUS          CHAR(1) NOT NULL DEFAULT 'A'
);
