SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS FUNCTION_MASTER (
    FUNCTION_ID     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FUNCTION_CODE   VARCHAR(20) NOT NULL UNIQUE,
    FUNCTION_NAME   VARCHAR(60) NOT NULL
);
