SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS MASTER_POLICY (
    MASTER_POLICY_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID          INT NOT NULL REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    MASTER_POLICY_NO    VARCHAR(40) NOT NULL UNIQUE,
    CUSTOMER_NO         VARCHAR(30) NOT NULL,
    CDBG_NO             VARCHAR(20),
    CD_BALANCE          NUMERIC(15,2) NOT NULL DEFAULT 0
);
