SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS BATCH_MASTER (
    BATCH_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         BIGINT NOT NULL REFERENCES USER_MASTER(USER_ID),
    PRODUCT_ID      INT NOT NULL REFERENCES PRODUCT_MASTER(PRODUCT_ID),
    FUNCTION_ID     INT NOT NULL REFERENCES FUNCTION_MASTER(FUNCTION_ID),
    FILE_NAME       VARCHAR(255) NOT NULL,
    TOTAL_RECORDS   INT NOT NULL DEFAULT 0,
    VALID_RECORDS   INT NOT NULL DEFAULT 0,
    INVALID_RECORDS INT NOT NULL DEFAULT 0,
    STATUS          VARCHAR(25) NOT NULL DEFAULT 'UPLOADED',
    CREATED_ON      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT ck_batch_master_total_records CHECK (TOTAL_RECORDS <= 200)
);
