SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS BATCH_DETAIL (
    DETAIL_ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID            BIGINT NOT NULL REFERENCES BATCH_MASTER(BATCH_ID) ON DELETE CASCADE,
    MASTER_POLICY_NO    VARCHAR(40) NOT NULL,
    ENGINE_NO           VARCHAR(30) NOT NULL,
    CHASSIS_NO          VARCHAR(30) NOT NULL,
    TC_NO               VARCHAR(30),
    INVOICE_NO          VARCHAR(30),
    TRANSIT_DATE        DATE,
    MAKE                VARCHAR(40),
    MODEL               VARCHAR(80),
    RECORD_STATUS       VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);
