SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS INVALID_RECORDS (
    INVALID_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATCH_ID        BIGINT NOT NULL REFERENCES BATCH_MASTER(BATCH_ID) ON DELETE CASCADE,
    DETAIL_ID       BIGINT NOT NULL REFERENCES BATCH_DETAIL(DETAIL_ID) ON DELETE CASCADE,
    TRANSIT_DATE    DATE,
    INVOICE_NO      VARCHAR(30),
    ENGINE_NO       VARCHAR(30),
    CHASSIS_NO      VARCHAR(30),
    ERROR_REMARKS   VARCHAR(255) NOT NULL
);
