SET search_path TO "motorportal";

CREATE TABLE IF NOT EXISTS PREMIUM_DETAILS (
    PREMIUM_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DETAIL_ID       BIGINT NOT NULL REFERENCES BATCH_DETAIL(DETAIL_ID) ON DELETE CASCADE,
    BASE_PREMIUM    NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADDON_PREMIUM   NUMERIC(12,2) NOT NULL DEFAULT 0,
    DISCOUNT        NUMERIC(12,2) NOT NULL DEFAULT 0,
    NET_PREMIUM     NUMERIC(12,2) NOT NULL DEFAULT 0
);
