SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS GST_DETAILS (
    GST_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PREMIUM_ID      BIGINT NOT NULL UNIQUE REFERENCES PREMIUM_DETAILS(PREMIUM_ID) ON DELETE CASCADE,
    GST_RATE        NUMERIC(5,2) NOT NULL DEFAULT 18.00,
    GST_AMOUNT      NUMERIC(12,2) NOT NULL DEFAULT 0,
    FINAL_PREMIUM   NUMERIC(12,2) NOT NULL DEFAULT 0
);
