SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS PROPOSAL_MASTER (
    PROPOSAL_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DETAIL_ID       BIGINT NOT NULL REFERENCES BATCH_DETAIL(DETAIL_ID) ON DELETE CASCADE,
    PROPOSAL_NO     VARCHAR(30) NOT NULL UNIQUE,
    PREMIUM_AMOUNT  NUMERIC(12,2) NOT NULL DEFAULT 0,
    STATUS          VARCHAR(25) NOT NULL DEFAULT 'PROPOSAL_CREATED',
    REMARKS         VARCHAR(120)
);
