SET search_path TO "motorportal";

CREATE TABLE IF NOT EXISTS PAYMENT_DETAILS (
    PAYMENT_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROPOSAL_ID         BIGINT NOT NULL REFERENCES PROPOSAL_MASTER(PROPOSAL_ID) ON DELETE CASCADE,
    MASTER_POLICY_ID    BIGINT NOT NULL REFERENCES MASTER_POLICY(MASTER_POLICY_ID),
    PF_REF_NO           VARCHAR(40),
    AMOUNT              NUMERIC(12,2) NOT NULL,
    PAYMENT_STATUS      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    TAGGED_ON           TIMESTAMP
);
