SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS POLICY_MASTER (
    POLICY_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROPOSAL_ID     BIGINT NOT NULL REFERENCES PROPOSAL_MASTER(PROPOSAL_ID),
    PAYMENT_ID      BIGINT NOT NULL REFERENCES PAYMENT_DETAILS(PAYMENT_ID),
    POLICY_NO       VARCHAR(40) NOT NULL UNIQUE,
    MAKE            VARCHAR(40),
    MODEL           VARCHAR(80),
    ENGINE_NO       VARCHAR(30) NOT NULL,
    CHASSIS_NO      VARCHAR(30) NOT NULL,
    PREMIUM         NUMERIC(12,2) NOT NULL DEFAULT 0,
    STATUS          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ISSUED_ON       TIMESTAMP NOT NULL DEFAULT now()
);
