SET search_path TO "motorportal";

CREATE TABLE IF NOT EXISTS POLICY_CERTIFICATE (
    CERT_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POLICY_ID       BIGINT NOT NULL REFERENCES POLICY_MASTER(POLICY_ID) ON DELETE CASCADE,
    CERT_PATH       VARCHAR(255) NOT NULL,
    GENERATED_ON    TIMESTAMP NOT NULL DEFAULT now()
);
