SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS REPORT_LOG (
    REPORT_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         BIGINT NOT NULL REFERENCES USER_MASTER(USER_ID),
    REPORT_TYPE     VARCHAR(40) NOT NULL,
    FROM_DATE       DATE,
    TO_DATE         DATE,
    GENERATED_ON    TIMESTAMP NOT NULL DEFAULT now()
);
