SET search_path TO "SGInsurance";

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    AUDIT_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         BIGINT NOT NULL REFERENCES USER_MASTER(USER_ID),
    ENTITY_NAME     VARCHAR(40) NOT NULL,
    ACTION          VARCHAR(20) NOT NULL,
    REF_ID          VARCHAR(40),
    TIMESTAMP       TIMESTAMP NOT NULL DEFAULT now()
);
