SET search_path TO "motorportal";

-- FK indexes
CREATE INDEX IF NOT EXISTS ix_master_policy_product_id ON MASTER_POLICY(PRODUCT_ID);

CREATE INDEX IF NOT EXISTS ix_batch_master_user_id ON BATCH_MASTER(USER_ID);
CREATE INDEX IF NOT EXISTS ix_batch_master_product_id ON BATCH_MASTER(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS ix_batch_master_function_id ON BATCH_MASTER(FUNCTION_ID);
CREATE INDEX IF NOT EXISTS ix_batch_master_created_on ON BATCH_MASTER(CREATED_ON);

CREATE INDEX IF NOT EXISTS ix_batch_detail_batch_id ON BATCH_DETAIL(BATCH_ID);
CREATE INDEX IF NOT EXISTS ix_batch_detail_engine_no ON BATCH_DETAIL(ENGINE_NO);
CREATE INDEX IF NOT EXISTS ix_batch_detail_chassis_no ON BATCH_DETAIL(CHASSIS_NO);
CREATE INDEX IF NOT EXISTS ix_batch_detail_master_policy_no ON BATCH_DETAIL(MASTER_POLICY_NO);

CREATE INDEX IF NOT EXISTS ix_invalid_records_batch_id ON INVALID_RECORDS(BATCH_ID);
CREATE INDEX IF NOT EXISTS ix_invalid_records_detail_id ON INVALID_RECORDS(DETAIL_ID);

CREATE INDEX IF NOT EXISTS ix_premium_details_detail_id ON PREMIUM_DETAILS(DETAIL_ID);

CREATE INDEX IF NOT EXISTS ix_gst_details_premium_id ON GST_DETAILS(PREMIUM_ID);

CREATE INDEX IF NOT EXISTS ix_proposal_master_detail_id ON PROPOSAL_MASTER(DETAIL_ID);

CREATE INDEX IF NOT EXISTS ix_payment_details_proposal_id ON PAYMENT_DETAILS(PROPOSAL_ID);
CREATE INDEX IF NOT EXISTS ix_payment_details_master_policy_id ON PAYMENT_DETAILS(MASTER_POLICY_ID);

CREATE INDEX IF NOT EXISTS ix_policy_master_proposal_id ON POLICY_MASTER(PROPOSAL_ID);
CREATE INDEX IF NOT EXISTS ix_policy_master_payment_id ON POLICY_MASTER(PAYMENT_ID);
CREATE INDEX IF NOT EXISTS ix_policy_master_policy_no ON POLICY_MASTER(POLICY_NO);
CREATE INDEX IF NOT EXISTS ix_policy_master_engine_no ON POLICY_MASTER(ENGINE_NO);
CREATE INDEX IF NOT EXISTS ix_policy_master_chassis_no ON POLICY_MASTER(CHASSIS_NO);

CREATE INDEX IF NOT EXISTS ix_policy_certificate_policy_id ON POLICY_CERTIFICATE(POLICY_ID);

CREATE INDEX IF NOT EXISTS ix_report_log_user_id ON REPORT_LOG(USER_ID);

CREATE INDEX IF NOT EXISTS ix_audit_log_user_id ON AUDIT_LOG(USER_ID);
CREATE INDEX IF NOT EXISTS ix_audit_log_entity_ref ON AUDIT_LOG(ENTITY_NAME, REF_ID);
