SET search_path TO "motorportal";

-- pgcrypto gives us a real bcrypt hash (compatible with BCrypt.Net-Next on the API side)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Admin user (admin / admin123)
INSERT INTO USER_MASTER (USERNAME, PASSWORD_HASH, ROLE, STATUS)
SELECT 'admin', crypt('admin123', gen_salt('bf')), 'ADMIN', 'A'
WHERE NOT EXISTS (SELECT 1 FROM USER_MASTER WHERE USERNAME = 'admin');

-- Products
INSERT INTO PRODUCT_MASTER (PRODUCT_CODE, PRODUCT_NAME, STATUS)
SELECT * FROM (VALUES
    ('CLASS_E', 'Motor Class-E', 'A'),
    ('CLASS_F', 'Motor Class-F', 'A'),
    ('EICHER',  'Eicher Motor',  'A')
) AS v(code, name, status)
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_MASTER WHERE PRODUCT_CODE = v.code);

-- Functions
INSERT INTO FUNCTION_MASTER (FUNCTION_CODE, FUNCTION_NAME)
SELECT * FROM (VALUES
    ('EXCEL_UPLOAD',  'Motor Excel Upload'),
    ('BATCH_SUMMARY', 'Motor Batch Summary'),
    ('REPORT',        'Motor Report'),
    ('SEARCH_PRINT',  'Search & Print Policy'),
    ('POLICY_CANCEL', 'Policy Cancel Upload')
) AS v(code, name)
WHERE NOT EXISTS (SELECT 1 FROM FUNCTION_MASTER WHERE FUNCTION_CODE = v.code);

-- Master policies (spread across the 3 products; one deliberately low balance)
INSERT INTO MASTER_POLICY (PRODUCT_ID, MASTER_POLICY_NO, CUSTOMER_NO, CDBG_NO, CD_BALANCE)
SELECT p.PRODUCT_ID, v.master_policy_no, v.customer_no, v.cdbg_no, v.cd_balance
FROM (VALUES
    ('CLASS_E', 'DL-3010/A/1485551', 'CUST00001', 'CDBG0001', 500000.00),
    ('CLASS_E', 'DL-3010/A/1485552', 'CUST00002', 'CDBG0002', 250000.00),
    ('CLASS_E', 'DL-3010/A/1485553', 'CUST00003', 'CDBG0003',   1500.00),
    ('CLASS_F', 'DL-3010/B/2285561', 'CUST00004', 'CDBG0004', 800000.00),
    ('CLASS_F', 'DL-3010/B/2285562', 'CUST00005', 'CDBG0005', 120000.00),
    ('CLASS_F', 'DL-3010/B/2285563', 'CUST00006', 'CDBG0006', 300000.00),
    ('EICHER',  'DL-3010/C/3385571', 'CUST00007', 'CDBG0007', 950000.00),
    ('EICHER',  'DL-3010/C/3385572', 'CUST00008', 'CDBG0008', 175000.00),
    ('EICHER',  'DL-3010/C/3385573', 'CUST00009', 'CDBG0009', 640000.00),
    ('EICHER',  'DL-3010/C/3385574', 'CUST00010', 'CDBG0010',  60000.00)
) AS v(product_code, master_policy_no, customer_no, cdbg_no, cd_balance)
JOIN PRODUCT_MASTER p ON p.PRODUCT_CODE = v.product_code
WHERE NOT EXISTS (SELECT 1 FROM MASTER_POLICY mp WHERE mp.MASTER_POLICY_NO = v.master_policy_no);

-- Sample batches: one fully PRINTED, one mid-pipeline (PROPOSAL_CREATED), one freshly UPLOADED
DO $$
DECLARE
    v_admin_id   BIGINT;
    v_class_e_id INT;
    v_class_f_id INT;
    v_upload_fn  INT;
    v_batch1     BIGINT;
    v_batch2     BIGINT;
    v_batch3     BIGINT;
    v_detail_id  BIGINT;
BEGIN
    SELECT USER_ID INTO v_admin_id FROM USER_MASTER WHERE USERNAME = 'admin';
    SELECT PRODUCT_ID INTO v_class_e_id FROM PRODUCT_MASTER WHERE PRODUCT_CODE = 'CLASS_E';
    SELECT PRODUCT_ID INTO v_class_f_id FROM PRODUCT_MASTER WHERE PRODUCT_CODE = 'CLASS_F';
    SELECT FUNCTION_ID INTO v_upload_fn FROM FUNCTION_MASTER WHERE FUNCTION_CODE = 'EXCEL_UPLOAD';

    IF NOT EXISTS (SELECT 1 FROM BATCH_MASTER WHERE FILE_NAME = 'seed_batch_uploaded.xlsx') THEN
        INSERT INTO BATCH_MASTER (USER_ID, PRODUCT_ID, FUNCTION_ID, FILE_NAME, TOTAL_RECORDS, VALID_RECORDS, INVALID_RECORDS, STATUS)
        VALUES (v_admin_id, v_class_e_id, v_upload_fn, 'seed_batch_uploaded.xlsx', 3, 0, 0, 'UPLOADED')
        RETURNING BATCH_ID INTO v_batch1;

        INSERT INTO BATCH_DETAIL (BATCH_ID, MASTER_POLICY_NO, ENGINE_NO, CHASSIS_NO, TC_NO, INVOICE_NO, TRANSIT_DATE, MAKE, MODEL, RECORD_STATUS)
        VALUES
            (v_batch1, 'DL-3010/A/1485551', 'ENG-SEED-0001', 'CHS-SEED-0001', 'TC0001', 'INV0001', CURRENT_DATE - 2, 'Maruti', 'Alto', 'PENDING'),
            (v_batch1, 'DL-3010/A/1485552', 'ENG-SEED-0002', 'CHS-SEED-0002', 'TC0002', 'INV0002', CURRENT_DATE - 2, 'Hyundai', 'i10', 'PENDING'),
            (v_batch1, 'BAD-POLICY-NO',      'ENG-SEED-0003', 'CHS-SEED-0003', 'TC0003', 'INV0003', CURRENT_DATE - 2, 'Tata', 'Nexon', 'PENDING');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM BATCH_MASTER WHERE FILE_NAME = 'seed_batch_proposal_created.xlsx') THEN
        INSERT INTO BATCH_MASTER (USER_ID, PRODUCT_ID, FUNCTION_ID, FILE_NAME, TOTAL_RECORDS, VALID_RECORDS, INVALID_RECORDS, STATUS)
        VALUES (v_admin_id, v_class_f_id, v_upload_fn, 'seed_batch_proposal_created.xlsx', 3, 2, 1, 'PROPOSAL_CREATED')
        RETURNING BATCH_ID INTO v_batch2;

        INSERT INTO BATCH_DETAIL (BATCH_ID, MASTER_POLICY_NO, ENGINE_NO, CHASSIS_NO, TC_NO, INVOICE_NO, TRANSIT_DATE, MAKE, MODEL, RECORD_STATUS)
        VALUES (v_batch2, 'DL-3010/B/2285561', 'ENG-SEED-0004', 'CHS-SEED-0004', 'TC0004', 'INV0004', CURRENT_DATE - 5, 'Eicher', 'Pro 2049', 'VALID')
        RETURNING DETAIL_ID INTO v_detail_id;

        INSERT INTO PREMIUM_DETAILS (DETAIL_ID, BASE_PREMIUM, ADDON_PREMIUM, DISCOUNT, NET_PREMIUM)
        VALUES (v_detail_id, 18000.00, 1500.00, 500.00, fn_calculate_net_premium(18000.00, 1500.00, 500.00));

        INSERT INTO GST_DETAILS (PREMIUM_ID, GST_RATE, GST_AMOUNT, FINAL_PREMIUM)
        SELECT pd.PREMIUM_ID, 18.00, g.gst_amount, g.final_premium
        FROM PREMIUM_DETAILS pd, LATERAL fn_calculate_gst(pd.NET_PREMIUM, 18.00) g
        WHERE pd.DETAIL_ID = v_detail_id;

        INSERT INTO PROPOSAL_MASTER (DETAIL_ID, PROPOSAL_NO, PREMIUM_AMOUNT, STATUS, REMARKS)
        SELECT v_detail_id, fn_generate_proposal_no(), gd.FINAL_PREMIUM, 'PROPOSAL_CREATED', 'Successful Proposal Created'
        FROM GST_DETAILS gd JOIN PREMIUM_DETAILS pd ON pd.PREMIUM_ID = gd.PREMIUM_ID
        WHERE pd.DETAIL_ID = v_detail_id;

        INSERT INTO BATCH_DETAIL (BATCH_ID, MASTER_POLICY_NO, ENGINE_NO, CHASSIS_NO, TC_NO, INVOICE_NO, TRANSIT_DATE, MAKE, MODEL, RECORD_STATUS)
        VALUES (v_batch2, 'DL-3010/B/2285562', 'ENG-SEED-0005', 'CHS-SEED-0005', 'TC0005', 'INV0005', CURRENT_DATE - 5, 'Eicher', 'Pro 3015', 'VALID');

        INSERT INTO BATCH_DETAIL (BATCH_ID, MASTER_POLICY_NO, ENGINE_NO, CHASSIS_NO, TC_NO, INVOICE_NO, TRANSIT_DATE, MAKE, MODEL, RECORD_STATUS)
        VALUES (v_batch2, 'DL-3010/B/2285561', 'ENG-SEED-0004', 'CHS-SEED-0004', 'TC0006', 'INV0006', CURRENT_DATE - 5, 'Eicher', 'Pro 2049', 'INVALID');

        INSERT INTO INVALID_RECORDS (BATCH_ID, DETAIL_ID, TRANSIT_DATE, INVOICE_NO, ENGINE_NO, CHASSIS_NO, ERROR_REMARKS)
        SELECT v_batch2, DETAIL_ID, TRANSIT_DATE, INVOICE_NO, ENGINE_NO, CHASSIS_NO, 'Duplicate vehicle within batch'
        FROM BATCH_DETAIL WHERE BATCH_ID = v_batch2 AND INVOICE_NO = 'INV0006';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM BATCH_MASTER WHERE FILE_NAME = 'seed_batch_printed.xlsx') THEN
        INSERT INTO BATCH_MASTER (USER_ID, PRODUCT_ID, FUNCTION_ID, FILE_NAME, TOTAL_RECORDS, VALID_RECORDS, INVALID_RECORDS, STATUS, CREATED_ON)
        VALUES (v_admin_id, v_class_e_id, v_upload_fn, 'seed_batch_printed.xlsx', 1, 1, 0, 'PRINTED', now() - interval '3 days')
        RETURNING BATCH_ID INTO v_batch3;

        INSERT INTO BATCH_DETAIL (BATCH_ID, MASTER_POLICY_NO, ENGINE_NO, CHASSIS_NO, TC_NO, INVOICE_NO, TRANSIT_DATE, MAKE, MODEL, RECORD_STATUS)
        VALUES (v_batch3, 'DL-3010/A/1485553', 'ENG-SEED-0006', 'CHS-SEED-0006', 'TC0007', 'INV0007', CURRENT_DATE - 8, 'Bajaj', 'RE', 'VALID')
        RETURNING DETAIL_ID INTO v_detail_id;

        INSERT INTO PREMIUM_DETAILS (DETAIL_ID, BASE_PREMIUM, ADDON_PREMIUM, DISCOUNT, NET_PREMIUM)
        VALUES (v_detail_id, 9000.00, 0, 0, 9000.00);

        INSERT INTO GST_DETAILS (PREMIUM_ID, GST_RATE, GST_AMOUNT, FINAL_PREMIUM)
        SELECT PREMIUM_ID, 18.00, 1620.00, 10620.00 FROM PREMIUM_DETAILS WHERE DETAIL_ID = v_detail_id;

        INSERT INTO PROPOSAL_MASTER (DETAIL_ID, PROPOSAL_NO, PREMIUM_AMOUNT, STATUS, REMARKS)
        VALUES (v_detail_id, fn_generate_proposal_no(), 10620.00, 'PROPOSAL_CREATED', 'Successful Proposal Created');

        INSERT INTO PAYMENT_DETAILS (PROPOSAL_ID, MASTER_POLICY_ID, PF_REF_NO, AMOUNT, PAYMENT_STATUS, TAGGED_ON)
        SELECT pr.PROPOSAL_ID, mp.MASTER_POLICY_ID, 'PFSEED000001', 10620.00, 'PROCESSED', now() - interval '2 days'
        FROM PROPOSAL_MASTER pr
        JOIN BATCH_DETAIL bd ON bd.DETAIL_ID = pr.DETAIL_ID
        JOIN MASTER_POLICY mp ON mp.MASTER_POLICY_NO = bd.MASTER_POLICY_NO
        WHERE pr.DETAIL_ID = v_detail_id;

        INSERT INTO POLICY_MASTER (PROPOSAL_ID, PAYMENT_ID, POLICY_NO, MAKE, MODEL, ENGINE_NO, CHASSIS_NO, PREMIUM, STATUS, ISSUED_ON)
        SELECT pr.PROPOSAL_ID, pd.PAYMENT_ID, fn_generate_policy_no('3010','A'), 'Bajaj', 'RE', 'ENG-SEED-0006', 'CHS-SEED-0006', 10620.00, 'ACTIVE', now() - interval '2 days'
        FROM PROPOSAL_MASTER pr
        JOIN PAYMENT_DETAILS pd ON pd.PROPOSAL_ID = pr.PROPOSAL_ID
        WHERE pr.DETAIL_ID = v_detail_id;

        INSERT INTO POLICY_CERTIFICATE (POLICY_ID, CERT_PATH, GENERATED_ON)
        SELECT POLICY_ID, '/certificates/seed-' || POLICY_ID || '.pdf', now() - interval '1 days'
        FROM POLICY_MASTER WHERE ENGINE_NO = 'ENG-SEED-0006';
    END IF;
END;
$$;
